# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2Q0MWZmOTA0ZDAzYWRlMjgyYzI0MDI5ZmQ1NjVjZDEzZTQ3YWU0ZmJjYTY5Nzc1YTMwN2Y3MmM3MDBjMjdkYmZkOWVmYzAyYmQ1NGFmZTZlODgwZDk3MmUyMjU0MDFiZjU4MWQ3YzM0NjI1NGU2ZjMxM2JmY2U2OWY1MDc3ZjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
